version: 2.1
jobs:
  build:
    docker:
      -  image: docker:dind
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t vedant.l/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true vedant.l/docker-react npm run test